services:
  tautulli:
    image: ghcr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      TZ: Europe/Stockholm
      PUID: 1005
      PGID: 1005
    networks:
      - media
    volumes:
      - ./data:/config
    ports:
      - 8181:8181

networks:
  media:
    external: true
