services:
  radarr-4k:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr-4k
    environment:
      TZ: Europe/Stockholm
      PUID: 1005
      PGID: 1005
      DOCKER_MODS: ghcr.io/themepark-dev/theme.park:radarr
      TP_THEME: space-gray
      TP_ADDON: radarr-4k-logo|radarr-4k-favicon
    networks:
      - downloads
    volumes:
      - ../../shared/scripts/linuxserver-media-gid.sh:/custom-cont-init.d/media-gid.sh:ro
      - ./data:/config
      - /mnt/downloads:/downloads
      - /mnt/media:/media
    ports:
      - 8208:7878

networks:
  downloads:
    external: true
