services:
  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: seerr
    restart: unless-stopped
    user: 1005:1005
    environment:
      TZ: Europe/Stockholm
      PORT: 8055
    networks:
      - media
    volumes:
      - ./data:/app/config
    ports:
      - 8055:8055

networks:
  media:
    external: true
