services:
  mylar3:
    image: ghcr.io/linuxserver/mylar3:latest
    container_name: mylar3
    environment:
      TZ: Europe/Stockholm
      PUID: 4000
      PGID: 4000
    networks:
      - downloads
    volumes:
      - ./data:/config/mylar
      - /mnt/downloads:/downloads
      - /mnt/media/Comics:/data/Comics
    ports:
      - 8090:8090

networks:
  downloads:
    external: true
