http:
  routers:
    nextcloud:
      rule: Host(`nextcloud.irken-empire.org`)
      entrypoints: websecure
      service: nextcloud

  services:
    nextcloud:
      loadbalancer:
        servers:
          - url: http://10.120.200.28:8008
