services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:8
    container_name: recyclarr
    restart: unless-stopped
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs: /tmp
    user: 1005:1005
    init: true
    environment:
      TZ: Europe/Stockholm
    networks:
      - default
      - downloads
    volumes:
      - ./data:/config
  apprise:
    image: ghcr.io/linuxserver/apprise-api:latest
    container_name: recyclarr-apprise
    environment:
      TZ: Europe/Stockholm
      PUID: 1005
      PGID: 1005
    volumes:
      - apprise_attachments:/apprise/attachments

volumes:
  apprise_attachments:

networks:
  downloads:
    external: true
